# Generated by Django 3.2.7 on 2021-11-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRubric',
            fields=[
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('super_category__name', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.category',),
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Надкатегория',
                'verbose_name_plural': 'Надкатегории',
                'ordering': ('name',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.category',),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='board.supercategory', verbose_name='Надкатегория'),
        ),
    ]
