# Generated by Django 3.2.7 on 2021-11-06 16:21

import board.utilites
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211104_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='bb',
            name='contacts',
            field=models.TextField(null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, upload_to=board.utilites.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='bb',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Выводить в списке?'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='board.subrubric', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=board.utilites.get_timestamp_path, verbose_name='Изображение')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.bb', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Дополнительная иллюстрация',
                'verbose_name_plural': 'Дополнительные иллюстрации',
            },
        ),
    ]
